os: linux

dist: focal

git:
  depth: 1

cache: false

language: node_js

node_js:
- node

install:
- npm install -g grunt-cli posthtml-cli posthtml-img-autosize
- npm install

script:
- posthtml KiraFolder/KiraPostHTML.html -o KiraFolder/KiraImgAutosizeCLI.html -u posthtml-img-autosize --posthtml-img-autosize.processEmptySize true
- grunt posthtml --verbose
- cat KiraFolder/KiraImgAutosizeCLI.html
- cat KiraFolder/KiraPostHTML.output.html
